# Generated by Django 5.1.2 on 2024-10-31 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapi', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowapi.project'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowapi.group'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowapi.project'),
        ),
    ]
