# Generated by Django 5.1.2 on 2024-10-29 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapi', '0002_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='workflowapi.group'),
        ),
    ]
