# Generated by Django 5.1.2 on 2024-10-30 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapi', '0003_project_assigned_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='workers',
            field=models.ManyToManyField(related_name='workflow_groups', related_query_name='workflow_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectworker',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workers', to='workflowapi.project'),
        ),
        migrations.AlterField(
            model_name='projectworker',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='workflowapi.user'),
        ),
        migrations.AlterUniqueTogether(
            name='projectworker',
            unique_together={('project_id', 'worker_id')},
        ),
    ]
