# Generated by Django 5.1.2 on 2024-10-30 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapi', '0004_group_workers_alter_projectworker_project_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupworker',
            unique_together={('group', 'worker')},
        ),
        migrations.AddField(
            model_name='groupworker',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_workers', to='workflowapi.group'),
        ),
        migrations.AddField(
            model_name='groupworker',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='workflowapi.user'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='workers',
            field=models.ManyToManyField(related_name='workflow_groups', through='workflowapi.GroupWorker', to='workflowapi.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workflowapi.group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='clientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowapi.client'),
        ),
        migrations.AlterModelTable(
            name='groupworker',
            table='workflowapi_groupworker',
        ),
        migrations.RemoveField(
            model_name='groupworker',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='groupworker',
            name='worker_id',
        ),
    ]
