# Generated by Django 5.1.2 on 2024-10-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapi', '0005_alter_groupworker_unique_together_groupworker_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupworker',
            old_name='group',
            new_name='group_id',
        ),
        migrations.AlterUniqueTogether(
            name='groupworker',
            unique_together={('group_id', 'worker')},
        ),
    ]
