# Generated by Django 5.1.2 on 2024-10-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapi', '0006_rename_group_groupworker_group_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupworker',
            old_name='worker',
            new_name='worker_id',
        ),
        migrations.AlterUniqueTogether(
            name='groupworker',
            unique_together={('group_id', 'worker_id')},
        ),
    ]
